services:
  perune:
    name: Perune
    checker:
      basedir: ./checkers/perune
      script: ./perune.checker.py
      setup: python3 -m pip install --break-system-packages -r requirements.txt
    vuln:
      basedir: ./services/perune
